name: Deploy to Azure Container Registry

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
  IMAGE_NAME: sabeco-demo-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
        build-args: |
          KEYVAULT_URL=${{ secrets.KEYVAULT_URL }}
          SQL_CONNECTION_STRING=${{ secrets.SQL_CONNECTION_STRING }}
          COSMOS_CONNECTION_STRING=${{ secrets.COSMOS_CONNECTION_STRING }}
          BLOB_CONNECTION_STRING=${{ secrets.BLOB_CONNECTION_STRING }}
          ACR_NAME=${{ secrets.ACR_NAME }}
          ACR_SUBSCRIPTION=${{ secrets.ACR_SUBSCRIPTION }}
          ACR_RG=${{ secrets.ACR_RG }}
          REDIS_CONNECTION_STRING=${{ secrets.REDIS_CONNECTION_STRING }}
